[package]
name = "pen-plotter"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "3.1", features = ["derive"] }
env_logger = "0.9.0"
eyre = "0.6.8"
log = "0.4.17"
nalgebra = "0.31.0"
